export const IPC_CHANNELS = {
	mainProcessMessage: "main-process-message",
	loadPreferences: "load-preferences",
	cameraError: "camera-error",
	videoStream: "video-stream",
	cameraWindowClosed: "camera-window-closed",
	shortcutError: "shortcut-error",
	updateMessage: "update-message",
	updateExercisePrompt: "update-exercise-prompt",
	updateColors: "update-colors",
	cameraMode: "camera-mode",
	faceTrackingData: "face-tracking-data",
	blinkDetected: "blink-detected",
	thresholdUpdated: "threshold-updated",
	playSound: "play-sound",
	currentPopupState: "current-popup-state",
	startBlinkReminders: "start-blink-reminders",
	stopBlinkReminders: "stop-blink-reminders",
	updatePopupPosition: "update-popup-position",
	updateInterval: "update-interval",
	updatePopupColors: "update-popup-colors",
	updatePopupTransparency: "update-popup-transparency",
	updateDarkMode: "update-dark-mode",
	updateCameraEnabled: "update-camera-enabled",
	updateCameraQuality: "update-camera-quality",
	updateAutoStopNoFaceEnabled: "update-auto-stop-no-face-enabled",
	updateAutoStopNoFaceMinutes: "update-auto-stop-no-face-minutes",
	updateEarCalibration: "update-ear-calibration",
	startEarCalibration: "start-ear-calibration",
	cancelEarCalibration: "cancel-ear-calibration",
	earCalibrationProgress: "ear-calibration-progress",
	earCalibrationComplete: "ear-calibration-complete",
	updateEyeExercisesEnabled: "update-eye-exercises-enabled",
	updateExerciseInterval: "update-exercise-interval",
	updateExercisePrompts: "update-exercise-prompts",
	updateLookAwayEnabled: "update-look-away-enabled",
	updateLookAwayInterval: "update-look-away-interval",
	updateLookAwayDuration: "update-look-away-duration",
	updatePopupMessage: "update-popup-message",
	updateKeyboardShortcut: "update-keyboard-shortcut",
	startCameraTracking: "start-camera-tracking",
	stopCameraTracking: "stop-camera-tracking",
	skipExercise: "skip-exercise",
	snoozeExercise: "snooze-exercise",
	skipLookAway: "skip-look-away",
	snoozeLookAway: "snooze-look-away",
	snoozeBlink: "snooze-blink",
	updateMgdMode: "update-mgd-mode",
	showCameraWindow: "show-camera-window",
	closeCameraWindow: "close-camera-window",
	showPopupEditor: "show-popup-editor",
	popupEditorSaved: "popup-editor-saved",
	resetPreferences: "reset-preferences",
	showSizeEditor: "show-size-editor",
	sizeSaved: "size-saved",
	updateSoundEnabled: "update-sound-enabled",
	updateSoundVolume: "update-sound-volume",
	updateLaunchAtLogin: "update-launch-at-login",
	updateHasCompletedOnboarding: "update-has-completed-onboarding",
	audioFinished: "audio-finished",
	requestVideoStream: "request-video-stream",
	loadBlinkStats: "load-blink-stats",
	requestBlinkStats: "request-blink-stats",
	subscribeBlinkStats: "subscribe-blink-stats",
	unsubscribeBlinkStats: "unsubscribe-blink-stats",
	resetBlinkStats: "reset-blink-stats",
	updateQuietHoursEnabled: "update-quiet-hours-enabled",
	updateQuietHoursStart: "update-quiet-hours-start",
	updateQuietHoursEnd: "update-quiet-hours-end",
	updatePauseOnFullscreen: "update-pause-on-fullscreen",
	focusPauseState: "focus-pause-state",
	updateBlinkRateCoachingEnabled: "update-blink-rate-coaching-enabled",
	updateBlinkRateThreshold: "update-blink-rate-threshold",
	updateLocale: "update-locale",
	applyI18n: "apply-i18n",
	debugPreviewOverlay: "debug-preview-overlay",
	debugPreviewSound: "debug-preview-sound",
	debugPreviewCheer: "debug-preview-cheer",
	debugSetShopReward: "debug-set-shop-reward",
	openGithubRepo: "open-github-repo",
	openGithubReleases: "open-github-releases",
	openExternalUrl: "open-external-url",
	getReleaseNotes: "get-release-notes",
	checkForUpdates: "check-for-updates",
	autoUpdateStatus: "auto-update-status",
	installUpdate: "install-update",
	exportDiagnostics: "export-diagnostics",
	exportBackup: "export-backup",
	importBackup: "import-backup",
	updateGoalsConfig: "update-goals-config",
	spendBlinkReward: "spend-blink-reward",
	shellReady: "shell-ready",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export const MAIN_RENDERER_RECEIVE_CHANNELS = [
	IPC_CHANNELS.mainProcessMessage,
	IPC_CHANNELS.loadPreferences,
	IPC_CHANNELS.cameraError,
	IPC_CHANNELS.videoStream,
	IPC_CHANNELS.cameraWindowClosed,
	IPC_CHANNELS.updateMessage,
	IPC_CHANNELS.faceTrackingData,
	IPC_CHANNELS.blinkDetected,
	IPC_CHANNELS.thresholdUpdated,
	IPC_CHANNELS.earCalibrationProgress,
	IPC_CHANNELS.earCalibrationComplete,
	IPC_CHANNELS.loadBlinkStats,
	IPC_CHANNELS.focusPauseState,
	IPC_CHANNELS.shortcutError,
	IPC_CHANNELS.autoUpdateStatus,
] as const;

export const MAIN_RENDERER_SEND_CHANNELS = [
	IPC_CHANNELS.startBlinkReminders,
	IPC_CHANNELS.stopBlinkReminders,
	IPC_CHANNELS.updatePopupPosition,
	IPC_CHANNELS.updateInterval,
	IPC_CHANNELS.updatePopupColors,
	IPC_CHANNELS.updatePopupTransparency,
	IPC_CHANNELS.updateDarkMode,
	IPC_CHANNELS.updateCameraEnabled,
	IPC_CHANNELS.updateCameraQuality,
	IPC_CHANNELS.updateAutoStopNoFaceEnabled,
	IPC_CHANNELS.updateAutoStopNoFaceMinutes,
	IPC_CHANNELS.updateEarCalibration,
	IPC_CHANNELS.startEarCalibration,
	IPC_CHANNELS.cancelEarCalibration,
	IPC_CHANNELS.updateEyeExercisesEnabled,
	IPC_CHANNELS.updateExerciseInterval,
	IPC_CHANNELS.updateExercisePrompts,
	IPC_CHANNELS.updateLookAwayEnabled,
	IPC_CHANNELS.updateLookAwayInterval,
	IPC_CHANNELS.updateLookAwayDuration,
	IPC_CHANNELS.updatePopupMessage,
	IPC_CHANNELS.updateKeyboardShortcut,
	IPC_CHANNELS.startCameraTracking,
	IPC_CHANNELS.stopCameraTracking,
	IPC_CHANNELS.skipExercise,
	IPC_CHANNELS.snoozeExercise,
	IPC_CHANNELS.skipLookAway,
	IPC_CHANNELS.snoozeLookAway,
	IPC_CHANNELS.snoozeBlink,
	IPC_CHANNELS.updateMgdMode,
	IPC_CHANNELS.showCameraWindow,
	IPC_CHANNELS.closeCameraWindow,
	IPC_CHANNELS.showPopupEditor,
	IPC_CHANNELS.popupEditorSaved,
	IPC_CHANNELS.resetPreferences,
	IPC_CHANNELS.showSizeEditor,
	IPC_CHANNELS.sizeSaved,
	IPC_CHANNELS.updateSoundEnabled,
	IPC_CHANNELS.updateSoundVolume,
	IPC_CHANNELS.updateLaunchAtLogin,
	IPC_CHANNELS.updateHasCompletedOnboarding,
	IPC_CHANNELS.audioFinished,
	IPC_CHANNELS.requestVideoStream,
	IPC_CHANNELS.requestBlinkStats,
	IPC_CHANNELS.subscribeBlinkStats,
	IPC_CHANNELS.unsubscribeBlinkStats,
	IPC_CHANNELS.resetBlinkStats,
	IPC_CHANNELS.updateQuietHoursEnabled,
	IPC_CHANNELS.updateQuietHoursStart,
	IPC_CHANNELS.updateQuietHoursEnd,
	IPC_CHANNELS.updatePauseOnFullscreen,
	IPC_CHANNELS.updateBlinkRateCoachingEnabled,
	IPC_CHANNELS.updateBlinkRateThreshold,
	IPC_CHANNELS.updateLocale,
	IPC_CHANNELS.debugPreviewOverlay,
	IPC_CHANNELS.debugPreviewSound,
	IPC_CHANNELS.debugPreviewCheer,
	IPC_CHANNELS.debugSetShopReward,
	IPC_CHANNELS.openGithubRepo,
	IPC_CHANNELS.openGithubReleases,
	IPC_CHANNELS.openExternalUrl,
	IPC_CHANNELS.checkForUpdates,
	IPC_CHANNELS.installUpdate,
	IPC_CHANNELS.updateGoalsConfig,
	IPC_CHANNELS.spendBlinkReward,
	IPC_CHANNELS.shellReady,
] as const;
