export const IPC_CHANNELS = {
	mainProcessMessage: "main-process-message",
	loadPreferences: "load-preferences",
	cameraError: "camera-error",
	videoStream: "video-stream",
	cameraWindowClosed: "camera-window-closed",
	stopCamera: "stop-camera",
	shortcutError: "shortcut-error",
	updateMessage: "update-message",
	updateColors: "update-colors",
	cameraMode: "camera-mode",
	faceTrackingData: "face-tracking-data",
	blinkDetected: "blink-detected",
	thresholdUpdated: "threshold-updated",
	playSound: "play-sound",
	currentPopupState: "current-popup-state",
	startBlinkReminders: "start-blink-reminders",
	stopBlinkReminders: "stop-blink-reminders",
	updatePopupPosition: "update-popup-position",
	updateInterval: "update-interval",
	updatePopupColors: "update-popup-colors",
	updatePopupTransparency: "update-popup-transparency",
	updateDarkMode: "update-dark-mode",
	updateCameraEnabled: "update-camera-enabled",
	updateCameraQuality: "update-camera-quality",
	updateEarCalibration: "update-ear-calibration",
	startEarCalibration: "start-ear-calibration",
	cancelEarCalibration: "cancel-ear-calibration",
	earCalibrationProgress: "ear-calibration-progress",
	earCalibrationComplete: "ear-calibration-complete",
	updateUseMediaPipe: "update-use-media-pipe",
	updateEyeExercisesEnabled: "update-eye-exercises-enabled",
	updateExerciseInterval: "update-exercise-interval",
	updatePopupMessage: "update-popup-message",
	updateKeyboardShortcut: "update-keyboard-shortcut",
	startCameraTracking: "start-camera-tracking",
	stopCameraTracking: "stop-camera-tracking",
	skipExercise: "skip-exercise",
	snoozeExercise: "snooze-exercise",
	updateMgdMode: "update-mgd-mode",
	showCameraWindow: "show-camera-window",
	closeCameraWindow: "close-camera-window",
	showPopupEditor: "show-popup-editor",
	popupEditorSaved: "popup-editor-saved",
	resetPreferences: "reset-preferences",
	showSizeEditor: "show-size-editor",
	sizeSaved: "size-saved",
	updateSoundEnabled: "update-sound-enabled",
	updateLaunchAtLogin: "update-launch-at-login",
	audioFinished: "audio-finished",
	requestVideoStream: "request-video-stream",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export const MAIN_RENDERER_RECEIVE_CHANNELS = [
	IPC_CHANNELS.mainProcessMessage,
	IPC_CHANNELS.loadPreferences,
	IPC_CHANNELS.cameraError,
	IPC_CHANNELS.videoStream,
	IPC_CHANNELS.cameraWindowClosed,
	IPC_CHANNELS.updateMessage,
	IPC_CHANNELS.faceTrackingData,
	IPC_CHANNELS.blinkDetected,
	IPC_CHANNELS.thresholdUpdated,
	IPC_CHANNELS.earCalibrationProgress,
	IPC_CHANNELS.earCalibrationComplete,
] as const;

export const MAIN_RENDERER_SEND_CHANNELS = [
	IPC_CHANNELS.startBlinkReminders,
	IPC_CHANNELS.stopBlinkReminders,
	IPC_CHANNELS.updatePopupPosition,
	IPC_CHANNELS.updateInterval,
	IPC_CHANNELS.updatePopupColors,
	IPC_CHANNELS.updatePopupTransparency,
	IPC_CHANNELS.updateDarkMode,
	IPC_CHANNELS.updateCameraEnabled,
	IPC_CHANNELS.updateCameraQuality,
	IPC_CHANNELS.updateEarCalibration,
	IPC_CHANNELS.startEarCalibration,
	IPC_CHANNELS.cancelEarCalibration,
	IPC_CHANNELS.updateUseMediaPipe,
	IPC_CHANNELS.updateEyeExercisesEnabled,
	IPC_CHANNELS.updateExerciseInterval,
	IPC_CHANNELS.updatePopupMessage,
	IPC_CHANNELS.updateKeyboardShortcut,
	IPC_CHANNELS.startCameraTracking,
	IPC_CHANNELS.stopCameraTracking,
	IPC_CHANNELS.skipExercise,
	IPC_CHANNELS.snoozeExercise,
	IPC_CHANNELS.updateMgdMode,
	IPC_CHANNELS.showCameraWindow,
	IPC_CHANNELS.closeCameraWindow,
	IPC_CHANNELS.showPopupEditor,
	IPC_CHANNELS.popupEditorSaved,
	IPC_CHANNELS.resetPreferences,
	IPC_CHANNELS.showSizeEditor,
	IPC_CHANNELS.sizeSaved,
	IPC_CHANNELS.updateSoundEnabled,
	IPC_CHANNELS.updateLaunchAtLogin,
	IPC_CHANNELS.audioFinished,
	IPC_CHANNELS.requestVideoStream,
] as const;
